### ISSUE TITLE
Nichts Besonderes hier

### ISSUE THREAD

**Issue by ghost** [thyed/MMM-Webuntis#13]
Hi. Ich nutze den Magic Mirror erst seit Kurzem und eines der ersten Module war das Webuntis Modul um den Stundenplan meiner Tochter anzeigen zu lassen. Das funktioniert wunderbar - vielen Dank! Ich lasse mir die nächsten 7 Tage anzeigen und in der Woche vor den Osterferien wurde mir jeden Tag einer weniger angezeigt (weil dann ja die Osterferien kamen). In den Ferien stand "Nichts Besonderes hier" als einziger Eintrag da und jetzt nach den Ferien kamen keine neuen Einträge - "Nichts Besonderes hier" wird immer noch angezeigt. Ein grübelnder Blick auf die (unveränderte) Konfig hat nicht geholfen, mittlerweile habe ich das Modul auch mal deinstalliert und wieder installiert, lande aber immer wieder bei der gleichen Anzeige. Hast Du eine Idee, woran das liegen könnte oder was ich falsch mache?
Dank und Gruß,
Chris

![MagicMirror²](https://github.com/thyed/MMM-Webuntis/assets/105111227/9ca67480-0ea8-4885-bf28-4d595aa85bdf)

**Comment by r3wald** [comment]
Hallo Chris,
ich hatte genau dasselbe Problem und hab mir einen Test gebaut, der sicherstellt, dass zumindest die Konfiguration korrekt ist. Vielleicht willst Du das mal ausprobieren:
https://github.com/r3wald/MMM-Webuntis/tree/feature/check-configuration
Im README unter 'Checking functionality' ist die Benutzung erklärt.
Viel Erfolg,
Robert

**Comment by ghost** [comment]
Hallo Robert,
besten Dank für Deine Antwort. Dann schau ich mal, ob ich das hinbekomme ;-)
Grüße,
Chris

**Comment by ghost** [comment]
"Leider" bekomme ich keine Fehlermeldung. Der Login funktioniert (wenn ich das Passwort in ein falsches Passwort ändere, bekomme ich z.B. die Meldung "Failed to login"). Bei korrektem Passwort bekomme ich folgende Meldung:

(...)
fetching timetable:
Error: Server didn't returned any result.
    at WebUntis._request (/opt/magicmirror/modules/MMM-Webuntis/node_modules/webuntis/index.js:720:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WebUntis.getOwnTimetableForToday (/opt/magicmirror/modules/MMM-Webuntis/node_modules/webuntis/index.js:300:16)

Meine Config sieht folgendermaßen aus:

{
        module: "MMM-Webuntis",
        position: "bottom_right",
        header: "Untis",
        config: { // see 'Configuration options' for more information
            students: [
                {
                    title: "Tochter",
                    school: "Schulkürzel",
                    username: "***",
                    password: "###",
                    server: "nessa.webuntis.com",
                    useClassTimetable: false
                },
                            ],
            days: 10,
            fetchInterval: 5*60*1000,
            showStartTime: false,
            showRegularLessons: false,
            showTeacher: true,
            shortSubject: false,
            debug: false
        }
    },   

Ich bin für jeden Hinweis dankbar...

**Comment by r3wald** [comment]
Du hast `useClassTimetable: false` in Deiner Konfiguration. Hast Du es schon mit `true` probiert?

Das `debug` bitte auch mal auf `true` setzen. In den Log-Ausgaben sollte dann die Daten des Stundenplans - so abrufbar - angezeigt werden.

Wenn das nichts bringt, dann schau mal bitte nach node_modules/webuntis/test.js. Aufruf mit:
```
SCHOOL=... UNTISUSER=... UNTISSECRET=... UNTISHOST=... node test.js
```
Klappt das?

Wenn auch das nicht funktioniert, würde ich mal eine andere Implementierung testen. Diese hier (Python) hat zumindest bei mir funktioniert: https://pypi.org/project/webuntis-cli/
Die Debug-Ausgaben dort sind recht ausführlich.

Viel Erfolg

Nachtrag: Sofern es den Stundenplan nur für die gesamte Klasse gibt, _muss_ `class` in der Konfiguration gesetzt werden. Sonst passiert gar nichts.

**Comment by ghost** [comment]
Ich habe den Fehler als solchen nicht gefunden. Der Server liefert auf die Anfrage schlicht keine Daten aus. Nachdem ich mich mit dem Account des Kindes angemeldet hatte, kamen die Daten. Nun kann es natürlich sein, dass das genauso sein soll - funktioniert für mich nun auch wunderbar. Bisher hatten wir den Eltern-Login hinterlegt, der bis zu den Osterferien auch geliefert hatte.
Herzlichen Dank für Deinen Input und Deine Hilfe. Als ich über das check Skript zum ersten Mal Daten angezeigt bekommen habe, habe ich mich sehr gefreut :-)
