### ISSUE TITLE
TypeError: WebUntis is not a constructor

### ISSUE THREAD

**Issue by rabbit83ka** [thyed/MMM-Webuntis#8]
Hi, nachdem das Modul jetzt lange Zeit fehlerfrei lief, bekomme ich seit einiger Zeit (vermutlich letzte Update von MagicMirror, bin mir aber nicht 100% sicher) folgende Fehlermeldung:

```
0|MagicMirror  | [25.04.2023 10:17.39.558] [ERROR] Whoops! There was an uncaught exception...
0|MagicMirror  | [25.04.2023 10:17.39.591] [ERROR] TypeError: WebUntis is not a constructor
0|MagicMirror  |     at Class.fetchLessonsLogin (/home/pi/MagicMirror/modules/MMM-Webuntis/node_helper.js:33:17)
0|MagicMirror  |     at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-Webuntis/node_helper.js:19:11)
0|MagicMirror  |     at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:107:11)
0|MagicMirror  |     at Socket.emit (node:events:513:28)
0|MagicMirror  |     at Socket.emitUntyped (/home/pi/MagicMirror/node_modules/socket.io/dist/typed-events.js:69:22)
0|MagicMirror  |     at /home/pi/MagicMirror/node_modules/socket.io/dist/socket.js:703:39
0|MagicMirror  |     at process.processTicksAndRejections (node:internal/process/task_queues:78:11)
```

Die Konfiguration habe ich nochmal geprüft, sollte alles stimmen, hat ja wie gesagt auch lange funktioniert. Gibt's eine Idee wo der Fehler liegt?

**Comment by r3wald** [comment]
MMM-Webuntis setzt auf eine Bibliothek namens Webuntis. Und die wurde Ende 2022 komplett umgebaut.
Ich vermute, Du hast MMM-Webuntis aktualisiert und vergessen in dem Ordner "npm install" aufzurufen. Damit würde Webuntis in der notwendigen Version installiert werden.

siehe https://github.com/SchoolUtils/WebUntis/releases

**Comment by rabbit83ka** [comment]
Danke für die Rückmeldung. npm install hat damals nichts geholfen, es gibt einen aktuell gepflegten und bei mir gut funktionierenden Fork von [HeikoGr](https://github.com/HeikoGr/MMM-Webuntis)
